### ISSUE TITLE
TrackingApi.kt SDK not initialized. You need to call initialize(Context) method before

### ISSUE THREAD

**Issue by timardex** [Mobile-Telematics/TelematicsApp-Android#31]
Hi,

First of all thanks for the great app!!

Secondly, Firebase Crashlytics found a crash regarding TrackingApi. I was trying to debug this but I wasn't able to figure out the source of the problem. This is the error:

`Caused by java.lang.IllegalStateException: SDK not initialized. You need to call initialize(Context) method before
       at com.raxeltelematics.v2.sdk.TrackingApi.checkInitialized(TrackingApi.kt:819)
       at com.raxeltelematics.v2.sdk.TrackingApi.getQueue$tracking_release(TrackingApi.kt:847)
       at com.raxeltelematics.v2.sdk.services.main.SdkServiceController.registerMovingController(SdkServiceController.kt:308)
       at com.raxeltelematics.v2.sdk.services.main.SdkServiceController.updateTracking(SdkServiceController.kt:259)
       at com.raxeltelematics.v2.sdk.services.main.SdkServiceController.create(SdkServiceController.kt:55)
       at com.raxeltelematics.v2.sdk.services.main.SdkService.onCreate(SdkService.kt:49)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:5060)
       at android.app.ActivityThread.-$$Nest$mhandleCreateService()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2425)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8741)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)`

It would be really helpful to know why is this happening and thanks in advanced!

**Comment by telematicsgig** [comment]
Thanks for bringing our attention to this bug issue; We have changed the way how the SDK has been integrated, and it helped to fix the crash. please check
