### ISSUE TITLE
App crashes when Android target SDK level set to 34

### ISSUE THREAD

**Issue by nickdjones** [Mobile-Telematics/TelematicsApp-Android#35]
This is a critical bug as it prevents submission to the Google Play Store for new applications. To replicate:

- Open in Android Studio Ladybug 2024.2.1 Patch 1
- Manually set JDK version to 17 to get around https://github.com/Mobile-Telematics/TelematicsApp-Android/issues/34
- Set `targetSdk = "34"` in `libs.versions.toml`
- Open app on device
- Error should appear:

```
FATAL EXCEPTION: main
Process: uk.co.gotmoves.driver, PID: 14217
java.lang.RuntimeException: Unable to create service com.raxeltelematics.v2.sdk.services.main.SdkService: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{3b5fe4 14217:uk.co.gotmoves.driver/u0a671} targetSDK=34
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5196)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2514)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:9063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{3b5fe4 14217:uk.co.gotmoves.driver/u0a671} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4882)
	at android.os.Parcel.readParcelable(Parcel.java:4864)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3064)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7248)
	at android.app.Service.startForeground(Service.java:775)
	at com.raxeltelematics.v2.sdk.utils.ContextUtils.startForeground(ContextUtils.kt:50)
	at com.raxeltelematics.v2.sdk.services.main.SdkServiceController.createOrUpdateNotification(SdkServiceController.kt:293)
	at com.raxeltelematics.v2.sdk.services.main.SdkServiceController.create(SdkServiceController.kt:54)
	at com.raxeltelematics.v2.sdk.services.main.SdkService.onCreate(SdkService.kt:49)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5183)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2514) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:230) 
	at android.os.Looper.loop(Looper.java:319) 
	at android.app.ActivityThread.main(ActivityThread.java:9063) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 
```

Let me know if I can be of any help in solving this.

Thanks

**Comment by telematicsgig** [comment]
Hi @nickdjones, ensure you updated the telematics SDK to the latest version before building the app.
Target version 34 is supported by the SDK version 2.2.260 and above.
